"""Abstract base classes for the TUI's UI adapter pattern.

``CLIController`` depends only on these interfaces; concrete Textual widgets
register themselves as virtual subclasses in ``widgets.py`` and ``app.py``
to avoid the metaclass conflict between Textual's ``_MessagePumpMeta`` and
``ABCMeta``.
"""

from abc import ABC, abstractmethod


class MessageHandle(ABC):
    @abstractmethod
    def append(self, chunk: str) -> None: ...
    @abstractmethod
    def set_content(self, text: str) -> None: ...
    @abstractmethod
    def finish(self) -> None: ...
    @abstractmethod
    def finish_with_summary(self, text: str) -> None: ...


class EphemeralHandle(ABC):
    @abstractmethod
    def dismiss(self) -> None: ...
    @abstractmethod
    def set_done(self) -> None: ...
    @abstractmethod
    def set_error(self) -> None: ...
    @abstractmethod
    def is_running(self) -> bool: ...
    @abstractmethod
    def mark_worker_done(self, idx: int) -> None: ...
    @abstractmethod
    def mark_worker_error(self, idx: int) -> None: ...
    @abstractmethod
    def update_worker_activity(self, idx: int, activity: str) -> None: ...
    @abstractmethod
    def set_communication(self, text: str | None) -> None: ...
    @abstractmethod
    def upgrade(self, label: str, summary: str) -> None: ...


class ThinkingHandle(ABC):
    @abstractmethod
    def dismiss(self) -> None: ...
    @abstractmethod
    def finish(self, summary: str) -> None: ...


class TurnStatusHandle(ABC):
    @abstractmethod
    def stop(self) -> None: ...

    @abstractmethod
    def update_context(self, context_tokens: int | None, cached_tokens: int | None) -> None: ...


class UIAdapter(ABC):
    @abstractmethod
    def add_message(self, role: str, content: str = "") -> MessageHandle: ...
    @abstractmethod
    def add_divider(self) -> None: ...
    @abstractmethod
    def add_turn_status_bar(self) -> TurnStatusHandle: ...
    @abstractmethod
    def add_ephemeral_block(
        self, communication: str, label: str, summary: str
    ) -> EphemeralHandle: ...
    @abstractmethod
    def add_worker_block(
        self, communication: str, worker_summaries: list[str]
    ) -> EphemeralHandle: ...
    @abstractmethod
    def add_thinking_block(self) -> ThinkingHandle: ...
    @abstractmethod
    def clear_messages(self) -> None: ...
    @abstractmethod
    def set_workspace(self, name: str) -> None: ...
    @abstractmethod
    def set_file_count(self, description: str) -> None: ...
    @abstractmethod
    def set_input_placeholder(self, text: str) -> None: ...
    @abstractmethod
    def add_input_class(self, cls: str) -> None: ...
    @abstractmethod
    def remove_input_class(self, cls: str) -> None: ...
    @abstractmethod
    def set_input_value(self, value: str, cursor: int | None = None) -> None: ...
    @abstractmethod
    def show_completion(self, matches: list[str], selected: int) -> None: ...
    @abstractmethod
    def hide_completion(self) -> None: ...
    @abstractmethod
    def show_workspace_panel(self, files: list[str]) -> None: ...
    @abstractmethod
    def show_attachment(self, label: str) -> None: ...
    @abstractmethod
    def hide_attachment(self) -> None: ...

    def stop_agent(self) -> None:
        """Cancel the running agent worker. No-op if nothing is running."""
