"""Interfaces shared across the controller/UI boundary of the TUI.

``CLIController`` depends only on the ``UIAdapter``-family interfaces below,
expressed as ``typing.Protocol``s. Protocols are structural: a class satisfies
one simply by having matching methods, with no inheritance or registration
required. That keeps the concrete Textual widgets (``app.py``, ``widgets.py``)
free of any metaclass entanglement with these interfaces, and free of
ceremony for what is, today, a single concrete implementation
(``OpenDataSciApp``).

``SubmitAction`` is the other direction of that boundary: the typed result
``CLIController.on_submit`` hands back to ``OpenDataSciApp`` so it knows what
to do next, in place of ad hoc string literals.
"""

from enum import Enum
from typing import TYPE_CHECKING, Awaitable, Callable, Protocol

if TYPE_CHECKING:
    from opendatasci._tui.config.config_tree import ConfigNode
    from opendatasci.tools.mcp import MCPServerSpec


class SubmitAction(str, Enum):
    """What ``OpenDataSciApp`` should do after ``CLIController.on_submit``.

    A ``str`` subclass so existing equality checks against plain strings
    (tests, logging) keep working, while call sites get a named, typo-proof
    symbol instead of a bare string literal.
    """

    NONE = ""
    RUN = "run"
    RESUME_INPUT = "resume_input"
    QUIT = "quit"


class MessageHandle(Protocol):
    async def append(self, chunk: str) -> None: ...
    async def set_content(self, text: str) -> None: ...
    async def finish(self) -> None: ...


class EphemeralHandle(Protocol):
    def dismiss(self) -> None: ...
    def set_done(self) -> None: ...
    def set_error(self) -> None: ...
    def is_running(self) -> bool: ...
    def mark_task_done(self, idx: int) -> None: ...
    def mark_task_error(self, idx: int) -> None: ...
    def update_task_activity(self, idx: int, activity: str) -> None: ...
    def set_communication(self, text: str | None) -> None: ...
    def upgrade(self, label: str, summary: str) -> None: ...


class ThinkingHandle(Protocol):
    def dismiss(self) -> None: ...
    def finish(self, summary: str) -> None: ...


class TurnStatusHandle(Protocol):
    def stop(self) -> None: ...
    def update_context(self, context_tokens: int | None, cached_tokens: int | None) -> None: ...


class PendingMessageHandle(Protocol):
    """A pinned indicator for a message queued while the agent was busy."""

    def remove(self) -> None: ...


class UIAdapter(Protocol):
    def add_message(self, role: str, content: str = "") -> MessageHandle: ...
    def add_divider(self) -> None: ...
    def add_turn_status_bar(self) -> TurnStatusHandle: ...
    def add_pending_message(self, text: str) -> PendingMessageHandle: ...
    def add_ephemeral_block(
        self, communication: str, label: str, summary: str
    ) -> EphemeralHandle: ...
    def add_task_block(self, communication: str, task_summaries: list[str]) -> EphemeralHandle: ...
    def add_thinking_block(self) -> ThinkingHandle: ...
    def clear_messages(self) -> None: ...
    def set_workspace(self, name: str) -> None: ...
    def set_file_count(self, description: str) -> None: ...
    def set_background_tasks(self, description: str) -> None: ...
    def set_model_info(self, description: str) -> None: ...
    def set_input_placeholder(self, text: str) -> None: ...
    def add_input_class(self, cls: str) -> None: ...
    def remove_input_class(self, cls: str) -> None: ...
    def set_input_value(self, value: str, cursor: int | None = None) -> None: ...
    def show_completion(self, matches: list[str], selected: int) -> None: ...
    def hide_completion(self) -> None: ...
    def show_workspace_panel(self, files: list[str]) -> None: ...
    def show_approval_prompt(self, description: str, heads_up: str) -> None: ...
    def show_attachment(self, label: str) -> None: ...
    def hide_attachment(self) -> None: ...
    def add_image_block(self, path: str, caption: str) -> None: ...
    def open_config_panel(
        self,
        root: "ConfigNode",
        initial_values: dict[str, str],
        start_path: list[str],
        on_apply: Callable[[dict[str, str], list["MCPServerSpec"] | None], Awaitable[str | None]],
        initial_mcp_servers: list["MCPServerSpec"] | None = None,
    ) -> None: ...

    def refresh_theme(self) -> None:
        """Re-apply the active theme palette (call after opendatasci._tui.theme.set_active)."""

    def refresh_tips(self) -> None:
        """Re-render the footer tips bar (call after opendatasci._tui.tips.set_enabled)."""

    def stop_agent(self) -> None:
        """Cancel the running agent worker. No-op if nothing is running."""
